module.exports = {
  localPlayerDefault: {
    id: "",
    gameId: "",
    name: "",
    ready: "",
    points: {},
  },
  remotePlayersDefault: [],
  gameDefault: {
    id: "",
    categories: [],
    rounds: 0,
    letters: [],
    scores: {},
    currentRound: 0,
  },
  categoriesNames: [
    "Names",
    "Animals",
    "Countries",
    "Food",
    "Brands",
    "Professions",
    "Objects",
    "Colors",
    "Cities",
    "Songs",
    "Sports",
    "Movies",
  ],
};
